export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: string;
  categorySlug: string;
  iconName: string;
  isPopular: boolean;
  collection: "calculators" | "developer" | "seo" | null;
  dateAdded: string; // YYYY-MM-DD
  monthlyUses: string;
  isImplemented?: boolean;
}

export interface Category {
  slug: string;
  name: string;
  description: string;
  iconName: string;
  toolCount: number;
  previewTools: string[];
}

export interface FAQItem {
  id: string;
  question: string;
  answer: string;
}

export const CATEGORIES: Category[] = [
  {
    slug: "seo-tools",
    name: "SEO Tools",
    description: "Optimize your website's search performance and schema visibility.",
    iconName: "Search",
    toolCount: 15,
    previewTools: ["Schema Generator", "Meta Generator"],
  },
  {
    slug: "developer-tools",
    name: "Developer Tools",
    description: "Format, convert, decode, and debug code, strings, and markup.",
    iconName: "Code",
    toolCount: 20,
    previewTools: ["JSON Formatter", "JWT Decoder"],
  },
  {
    slug: "calculators",
    name: "Calculators",
    description: "Fast mathematical computations for health, finance, and age.",
    iconName: "Calculator",
    toolCount: 24,
    previewTools: ["Age Calculator", "SIP Calculator"],
  },
  {
    slug: "text-tools",
    name: "Text Tools",
    description: "Count words, format layouts, convert cases, and run diff checks.",
    iconName: "FileText",
    toolCount: 12,
    previewTools: ["Word Counter", "Case Converter"],
  },
  {
    slug: "data-tools",
    name: "Data Tools",
    description: "Clean, parse, convert, and format CSV, XML, and JSON datasets.",
    iconName: "Database",
    toolCount: 8,
    previewTools: ["CSV Cleaner", "XML Formatter"],
  },
  {
    slug: "pdf-tools",
    name: "PDF Tools",
    description: "Merge, compress, extract, and convert PDF documents quickly.",
    iconName: "FileSpreadsheet",
    toolCount: 12,
    previewTools: ["PDF Merger", "PDF Compressor"],
  },
  {
    slug: "image-tools",
    name: "Image Tools",
    description: "Compress, resize, convert formats, and optimize web images.",
    iconName: "Image",
    toolCount: 10,
    previewTools: ["Image Compressor", "WebP Converter"],
  },
  {
    slug: "business-tools",
    name: "Business Tools",
    description: "Create professional PDF invoices, client quotes, and payment receipts.",
    iconName: "Briefcase",
    toolCount: 3,
    previewTools: ["Invoice Generator", "Quote Generator"],
  },
];

export const TOOLS: Tool[] = [
  // Calculators
  {
    slug: "typing-test",
    name: "Typing Test",
    description: "Check your typing speed (WPM) and accuracy online with multiple test modes and personal best tracking.",
    category: "Calculators",
    categorySlug: "calculators",
    iconName: "Keyboard",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-23",
    monthlyUses: "32.4K uses/mo",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    description: "Calculate monthly loan Equated Monthly Installments (EMI) for home, car, or personal loans.",
    category: "Calculators",
    categorySlug: "calculators/finance",
    iconName: "Calculator",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-21",
    monthlyUses: "28.5K uses/mo",
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate standard monthly payments, and model savings from extra monthly payments.",
    category: "Calculators",
    categorySlug: "calculators/finance",
    iconName: "Calculator",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-21",
    monthlyUses: "16.4K uses/mo",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index (BMI) and check classification, healthy range, and Asian thresholds.",
    category: "Calculators",
    categorySlug: "calculators/health",
    iconName: "Activity",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-23",
    monthlyUses: "22.4K uses/mo",
  },
  {
    slug: "calorie-calculator",
    name: "Calorie Calculator",
    description: "Calculate your daily calorie needs (BMR & TDEE) and target intake based on your goals.",
    category: "Calculators",
    categorySlug: "calculators/health",
    iconName: "Flame",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-23",
    monthlyUses: "18.6K uses/mo",
  },
  {
    slug: "gpa-calculator",
    name: "GPA Calculator",
    description: "Calculate your Grade Point Average (GPA) on the unweighted 4.0 scale with custom courses and grades.",
    category: "Calculators",
    categorySlug: "calculators/education",
    iconName: "GraduationCap",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-23",
    monthlyUses: "20.1K uses/mo",
  },
  {
    slug: "cgpa-calculator",
    name: "CGPA Calculator",
    description: "Calculate CGPA on the 10-point scale and convert to percentage using university-specific formulas.",
    category: "Calculators",
    categorySlug: "calculators/education",
    iconName: "BookOpen",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-23",
    monthlyUses: "24.2K uses/mo",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age in years, months, weeks, and days based on your birthdate.",
    category: "Calculators",
    categorySlug: "calculators",
    iconName: "Calendar",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-03-10",
    monthlyUses: "12.4K uses/mo",
  },
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    description: "Estimate the future returns of your Systematic Investment Plan (SIP) investments.",
    category: "Calculators",
    categorySlug: "calculators/finance",
    iconName: "TrendingUp",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-04-12",
    monthlyUses: "8.2K uses/mo",
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    description: "Calculate compound interest with any compounding frequency. Compare simple vs compound interest, see year-by-year growth.",
    category: "Calculators",
    categorySlug: "calculators/finance",
    iconName: "TrendingUp",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-21",
    monthlyUses: "9.5K uses/mo",
  },
  {
    slug: "retirement-calculator",
    name: "Retirement Calculator",
    description: "Calculate your retirement corpus, expected monthly income, and see if your current savings are on track.",
    category: "Calculators",
    categorySlug: "calculators/finance",
    iconName: "TrendingUp",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-24",
    monthlyUses: "11.2K uses/mo",
  },
  {
    slug: "swp-calculator",
    name: "SWP Calculator",
    description: "Calculate how long your investment corpus will last with systematic monthly withdrawals, or find the maximum safe monthly withdrawal amount.",
    category: "Calculators",
    categorySlug: "calculators/finance",
    iconName: "TrendingDown",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-24",
    monthlyUses: "12.4K uses/mo",
  },
  {
    slug: "net-worth-calculator",
    name: "Net Worth Calculator",
    description: "Calculate your net worth by entering your assets and liabilities. See your asset breakdown, track your financial health, and save your data locally.",
    category: "Calculators",
    categorySlug: "calculators/finance",
    iconName: "Briefcase",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-24",
    monthlyUses: "15.6K uses/mo",
  },
  {
    slug: "break-even-calculator",
    name: "Break Even Calculator",
    description: "Calculate your business break-even point in units and revenue. Enter fixed costs, variable costs, and selling price to get your BEP with a cost-revenue chart.",
    category: "Calculators",
    categorySlug: "calculators/finance",
    iconName: "TrendingUp",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-06-24",
    monthlyUses: "14.2K uses/mo",
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Compute standard percentage values, increases, decreases, and fractions.",
    category: "Calculators",
    categorySlug: "calculators",
    iconName: "Percent",
    isPopular: false,
    collection: "calculators",
    dateAdded: "2026-06-18",
    monthlyUses: "4.5K uses/mo",
    isImplemented: false,
  },

  // Developer Tools
  {
    slug: "json-compare",
    name: "JSON Compare",
    description: "Compare two JSON objects side-by-side with highlighted diffs for added, removed, and changed keys.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "FileDiff",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-06-25",
    monthlyUses: "28.4K uses/mo",
    isImplemented: true,
  },
  {
    slug: "json-viewer",
    name: "JSON Viewer",
    description: "Visualize and navigate JSON data as an interactive collapsible tree with search and key path copying.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "TreePine",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-06-26",
    monthlyUses: "31.2K uses/mo",
    isImplemented: true,
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder & Decoder",
    description: "Encode text or files to Base64 and decode Base64 strings back to text, images, or files instantly.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "FileCode",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-06-27",
    monthlyUses: "42.8K uses/mo",
    isImplemented: true,
  },
  {
    slug: "url-encoder",
    name: "URL Encoder & Decoder",
    description: "Encode special characters in URLs, decode percent-encoded strings, and parse URL query parameters.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Link2",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-06-28",
    monthlyUses: "22.1K uses/mo",
    isImplemented: true,
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate cryptographically secure v4 UUIDs instantly in bulk or single format with custom casing.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Fingerprint",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-06-29",
    monthlyUses: "35.6K uses/mo",
    isImplemented: true,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 cryptographic hashes from text or files simultaneously.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Key",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-06-30",
    monthlyUses: "48.2K uses/mo",
    isImplemented: true,
  },
  {
    slug: "unix-timestamp-converter",
    name: "Unix Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates and vice versa with live counter and timezone support.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Clock",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-01",
    monthlyUses: "51.8K uses/mo",
    isImplemented: true,
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and indent raw SQL queries online with support for multiple SQL dialects and keyword casing.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Wand2",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-02",
    monthlyUses: "39.4K uses/mo",
    isImplemented: true,
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    description: "Format, beautify, and minify HTML markup with configurable indentation and sandboxed live preview.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Code",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-03",
    monthlyUses: "44.1K uses/mo",
    isImplemented: true,
  },
  {
    slug: "css-formatter",
    name: "CSS Formatter",
    description: "Beautify, sort properties, and minify CSS, SCSS, and Less code online for clean stylesheets.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Palette",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-04",
    monthlyUses: "41.6K uses/mo",
    isImplemented: true,
  },
  {
    slug: "javascript-formatter",
    name: "JavaScript Formatter",
    description: "Format, beautify, and minify JavaScript and TypeScript code with configurable brace and quote styles.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "FileCode2",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-05",
    monthlyUses: "47.3K uses/mo",
    isImplemented: true,
  },
  {
    slug: "duplicate-row-remover",
    name: "Duplicate Row Remover",
    description: "Remove duplicate lines from text or duplicate rows from CSV data with column-based key matching.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "FilterX",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-06",
    monthlyUses: "56.4K uses/mo",
    isImplemented: true,
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON objects or arrays with automatic delimiter detection and table preview.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "FileJson",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-07",
    monthlyUses: "62.1K uses/mo",
    isImplemented: true,
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON arrays to flat CSV format with nested object dot-notation flattening and column filtering.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "FileSpreadsheet",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-08",
    monthlyUses: "59.8K uses/mo",
    isImplemented: true,
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Format, beautify, and minify XML markup with real-time syntax validation and comment preservation.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "FileCode",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-09",
    monthlyUses: "38.5K uses/mo",
    isImplemented: true,
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate 1D barcodes in 8 formats including Code 128, EAN-13, and UPC-A with SVG and PNG export.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Barcode",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-10",
    monthlyUses: "54.2K uses/mo",
    isImplemented: true,
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description: "Pick pixel colors from images with magnifying loupe, extract dominant palettes, and convert color values.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "Pipette",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-11",
    monthlyUses: "71.9K uses/mo",
    isImplemented: true,
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Create custom QR codes for URLs, WiFi, vCards, and text with custom colors and logo overlay.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "QrCode",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-12",
    monthlyUses: "83.4K uses/mo",
    isImplemented: true,
  },
  {
    slug: "flexbox-generator",
    name: "Flexbox Generator",
    description: "Build CSS flexbox layouts visually with real-time preview, item overrides, and clean CSS code generation.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Layout",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-13",
    monthlyUses: "67.8K uses/mo",
    isImplemented: true,
  },
  {
    slug: "css-grid-generator",
    name: "CSS Grid Generator",
    description: "Design 2D CSS grid layouts visually with column/row track editors, template area naming, and presets.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Grid",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-07-14",
    monthlyUses: "79.1K uses/mo",
    isImplemented: true,
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    description: "Calculate Return on Investment, annualized gains, and marketing ROAS with interactive growth charts.",
    category: "Calculators",
    categorySlug: "calculators",
    iconName: "TrendingUp",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-07-15",
    monthlyUses: "88.4K uses/mo",
    isImplemented: true,
  },
  {
    slug: "profit-margin-calculator",
    name: "Profit Margin Calculator",
    description: "Calculate gross, operating, and net profit margins alongside markup percentage breakdowns.",
    category: "Calculators",
    categorySlug: "calculators",
    iconName: "PieChart",
    isPopular: true,
    collection: "calculators",
    dateAdded: "2026-07-16",
    monthlyUses: "92.1K uses/mo",
    isImplemented: true,
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description: "Create professional PDF invoices with custom line items, tax rates, logos, and instant PDF download.",
    category: "Business Tools",
    categorySlug: "business-tools",
    iconName: "FileText",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-17",
    monthlyUses: "104.5K uses/mo",
    isImplemented: true,
  },
  {
    slug: "quote-generator",
    name: "Quote Generator",
    description: "Generate price estimates and quotations with line items, valid dates, and downloadable PDF export.",
    category: "Business Tools",
    categorySlug: "business-tools",
    iconName: "FileSpreadsheet",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-18",
    monthlyUses: "73.2K uses/mo",
    isImplemented: true,
  },
  {
    slug: "receipt-generator",
    name: "Receipt Generator",
    description: "Create official payment receipts with payment method chips, paid watermarks, and instant PDF export.",
    category: "Business Tools",
    categorySlug: "business-tools",
    iconName: "Receipt",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-19",
    monthlyUses: "81.9K uses/mo",
    isImplemented: true,
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Clean, format, validate, and prettify raw JSON code with syntax nesting.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Braces",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-02-01",
    monthlyUses: "38.1K uses/mo",
    isImplemented: false,
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JSON Web Tokens (JWT) to inspect header, payload, and signature values.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "ShieldAlert",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-05-18",
    monthlyUses: "24.6K uses/mo",
    isImplemented: false,
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions against target strings with highlight matching.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Terminal",
    isPopular: true,
    collection: "developer",
    dateAdded: "2026-05-20",
    monthlyUses: "18.9K uses/mo",
    isImplemented: false,
  },
  {
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description: "Decode cron schedules into readable English summaries and execution timelines.",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    iconName: "Clock",
    isPopular: false,
    collection: null,
    dateAdded: "2026-06-19",
    monthlyUses: "5.2K uses/mo",
    isImplemented: false,
  },

  // SEO Tools
  {
    slug: "schema-generator",
    name: "Schema Generator",
    description: "Generate structured JSON-LD markup for articles, FAQs, products, and organizations.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Search",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-01-15",
    monthlyUses: "14.2K uses/mo",
  },
  {
    slug: "faq-schema-generator",
    name: "FAQ Schema Generator",
    description: "Generate structured FAQ JSON-LD schema markup for search visibility.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "HelpCircle",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-06-18",
    monthlyUses: "8.4K uses/mo",
  },
  {
    slug: "breadcrumb-schema-generator",
    name: "Breadcrumb Schema Generator",
    description: "Create breadcrumb schema lists to show hierarchy in Google Search results.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Map",
    isPopular: false,
    collection: "seo",
    dateAdded: "2026-06-19",
    monthlyUses: "6.1K uses/mo",
  },
  {
    slug: "meta-title-generator",
    name: "Meta Title Generator",
    description: "Write perfect titles for web pages matching Google's character lengths.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "FileText",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-06-20",
    monthlyUses: "11.2K uses/mo",
  },
  {
    slug: "meta-description-generator",
    name: "Meta Description Generator",
    description: "Create engaging meta descriptions that increase organic click-through rates.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Search",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-06-21",
    monthlyUses: "14.5K uses/mo",
  },
  {
    slug: "open-graph-generator",
    name: "Open Graph Generator",
    description: "Generate Open Graph meta tags and preview card layouts for social sharing.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Share2",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-06-23",
    monthlyUses: "16.8K uses/mo",
  },
  {
    slug: "twitter-card-generator",
    name: "Twitter Card Generator",
    description: "Generate Twitter Card meta tags and preview simulated cards in light and dark modes.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Share2",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-06-23",
    monthlyUses: "12.4K uses/mo",
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Generate a valid robots.txt file with a visual rule builder. Block bots, allow crawlers, add sitemap, and test URLs.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Settings",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-05-02",
    monthlyUses: "9.8K uses/mo",
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Generator",
    description: "Preview and build custom HTML meta tags for Google and social media previewing.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Globe",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-05-10",
    monthlyUses: "11.5K uses/mo",
    isImplemented: false,
  },
  {
    slug: "sitemap-generator",
    name: "Sitemap Generator",
    description: "Generate a valid XML sitemap from your URLs. Add URLs in bulk or one by one, set priority and change frequency, and download a ready-to-submit sitemap.xml.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Map",
    isPopular: false,
    collection: null,
    dateAdded: "2026-06-20",
    monthlyUses: "6.4K uses/mo",
  },
  {
    slug: "canonical-tag-checker",
    name: "Canonical Tag Checker",
    description: "Check if any webpage has a canonical tag, whether it is self-referencing, and if there are redirect issues.",
    category: "SEO Tools",
    categorySlug: "seo-tools",
    iconName: "Link",
    isPopular: true,
    collection: "seo",
    dateAdded: "2026-06-23",
    monthlyUses: "7.8K uses/mo",
  },

  // Data Tools
  {
    slug: "csv-cleaner",
    name: "CSV Cleaner",
    description: "Format, filter, strip commas, and validate CSV tabular datasets online.",
    category: "Data Tools",
    categorySlug: "data-tools",
    iconName: "FileSpreadsheet",
    isPopular: true,
    collection: null,
    dateAdded: "2026-04-18",
    monthlyUses: "7.8K uses/mo",
    isImplemented: false,
  },
  
  // Text Tools
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, paragraphs, and estimated reading times.",
    category: "Text Tools",
    categorySlug: "text-tools",
    iconName: "FileText",
    isPopular: true,
    collection: null,
    dateAdded: "2026-03-25",
    monthlyUses: "15.3K uses/mo",
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert string inputs to UPPERCASE, lowercase, Title Case, or camelCase.",
    category: "Text Tools",
    categorySlug: "text-tools",
    iconName: "Type",
    isPopular: false,
    collection: null,
    dateAdded: "2026-06-12",
    monthlyUses: "6.1K uses/mo",
  },
  {
    slug: "character-counter",
    name: "Character Counter",
    description: "Count characters with and without spaces, and check social media limit constraints.",
    category: "Text Tools",
    categorySlug: "text-tools",
    iconName: "Hash",
    isPopular: true,
    collection: null,
    dateAdded: "2026-06-21",
    monthlyUses: "12.4K uses/mo",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Merge multiple PDF files into one online in the order you want.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "FileText",
    isPopular: true,
    collection: null,
    dateAdded: "2026-06-21",
    monthlyUses: "24.5K uses/mo",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF file into individual pages or custom page ranges.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "Scissors",
    isPopular: true,
    collection: null,
    dateAdded: "2026-06-21",
    monthlyUses: "19.8K uses/mo",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages into high-quality JPG or PNG image files online.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "Image",
    isPopular: true,
    collection: null,
    dateAdded: "2026-06-22",
    monthlyUses: "22.1K uses/mo",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG, PNG, or WEBP images into a PDF document online in your browser.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "Images",
    isPopular: true,
    collection: null,
    dateAdded: "2026-06-23",
    monthlyUses: "15.3K uses/mo",
  },
  {
    slug: "extract-pdf-pages",
    name: "Extract PDF Pages",
    description: "Extract specific pages from a PDF document to create a new one online.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "FileSpreadsheet",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-10",
    monthlyUses: "18.2K uses/mo",
    isImplemented: true,
  },
  {
    slug: "delete-pdf-pages",
    name: "Delete PDF Pages",
    description: "Remove unwanted or blank pages from a PDF document easily.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "Trash2",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-10",
    monthlyUses: "16.4K uses/mo",
    isImplemented: true,
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove passwords and security restrictions from protected PDF files online.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "Unlock",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-10",
    monthlyUses: "22.5K uses/mo",
    isImplemented: true,
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Secure your PDF documents with custom passwords and permissions.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "Lock",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-10",
    monthlyUses: "14.8K uses/mo",
    isImplemented: true,
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file sizes safely while preserving maximum visual quality.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "FileArchive",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-10",
    monthlyUses: "32.1K uses/mo",
    isImplemented: true,
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Edit PDF files online for free. Add text, drawings, highlights, and annotations locally.",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
    iconName: "Edit",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-10",
    monthlyUses: "45.2K uses/mo",
    isImplemented: true,
  },
  // Image Tools
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPG, PNG, and WEBP images online without losing quality. Adjust compression level and preview before/after in a split view.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "Image",
    isPopular: true,
    collection: null,
    dateAdded: "2026-06-24",
    monthlyUses: "28.5K uses/mo",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize JPG, PNG, WEBP, and GIF images to exact pixel dimensions, percentage scale, or social media preset dimensions.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "Scaling",
    isPopular: true,
    collection: null,
    dateAdded: "2026-06-24",
    monthlyUses: "24.2K uses/mo",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert images between JPG, PNG, WEBP, and GIF formats online. Batch convert multiple files, adjust quality, and download instantly.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "ArrowRightLeft",
    isPopular: true,
    collection: null,
    dateAdded: "2026-06-24",
    monthlyUses: "18.4K uses/mo",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop JPG, PNG, and WEBP images visually with ratio presets, custom selection boxes, and rotation.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "Crop",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-20",
    monthlyUses: "38.2K uses/mo",
    isImplemented: true,
  },
  {
    slug: "image-watermark",
    name: "Image Watermark",
    description: "Add text or logo watermarks to your images. Customise placement, opacity, rotation, and tile grids.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "Sparkles",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-21",
    monthlyUses: "29.4K uses/mo",
    isImplemented: true,
  },
  {
    slug: "metadata-remover",
    name: "Metadata Remover",
    description: "Inspect and strip EXIF metadata, camera details, and GPS coordinates from your photos online.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "EyeOff",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-22",
    monthlyUses: "31.9K uses/mo",
    isImplemented: true,
  },
  {
    slug: "webp-converter",
    name: "WebP Converter",
    description: "Convert JPG, PNG, and GIF images to optimized WebP format to speed up web pages.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "FileImage",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-23",
    monthlyUses: "47.5K uses/mo",
    isImplemented: true,
  },
  {
    slug: "avif-converter",
    name: "AVIF Converter",
    description: "Convert images to high-compression AVIF files in your browser, with an automatic check that your browser really produced AVIF.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "Zap",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-24",
    monthlyUses: "34.1K uses/mo",
    isImplemented: true,
  },
  {
    slug: "svg-optimizer",
    name: "SVG Optimizer",
    description: "Optimize and minify SVG vectors to strip metadata, editor data, and reduce size autoritatively.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "Code",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-25",
    monthlyUses: "52.8K uses/mo",
    isImplemented: true,
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert SVG vectors to high-resolution PNG images in your browser, at any scale or target width.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "FileOutput",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-26",
    monthlyUses: "41.2K uses/mo",
    isImplemented: true,
  },
  {
    slug: "ico-generator",
    name: "ICO Generator",
    description: "Convert images to Windows ICO format with standard embedded sizes (16px to 256px) for favicons.",
    category: "Image Tools",
    categorySlug: "image-tools",
    iconName: "Grid",
    isPopular: true,
    collection: null,
    dateAdded: "2026-07-27",
    monthlyUses: "44.6K uses/mo",
    isImplemented: true,
  }
];

export const FAQS: FAQItem[] = [
  {
    id: "faq-1",
    question: "What is MicroTool?",
    answer: "MicroTool is a free collection of online tools for everyday tasks: calculators, PDF and image utilities, developer formatters, SEO generators and text tools. Nearly every tool runs directly in your browser, so your input is not uploaded anywhere.",
  },
  {
    id: "faq-2",
    question: "Who should use these tools?",
    answer: "These tools are designed for web developers, SEO specialists, writers, students, and professionals who need quick calculations or string operations in their daily work, without the friction of heavy desktop software.",
  },
  {
    id: "faq-3",
    question: "Are the tools free?",
    answer: "Yes. Every tool is free with no usage caps, no premium tier and no watermark on what you produce. No registration, email address or card details are required. The site is funded by advertising.",
  },
  {
    id: "faq-4",
    question: "How are results calculated?",
    answer: "Our tools use standard mathematical formulas and verified client-side algorithms (such as WHO BMI benchmarks or compound interest formulas). Results are processed instantly in your browser to guarantee speed, consistency, and privacy.",
  },
  {
    id: "faq-5",
    question: "Do I need to create an account?",
    answer: "No. You do not need to register, log in, or create an account to use our tools. Every utility is immediately accessible to all users without any signup wall.",
  },
  {
    id: "faq-6",
    question: "Is my data stored or shared?",
    answer: "Almost never. Your input is processed locally in your browser, so it is not uploaded and we cannot see it. Two PDF tools are the exception — Compress PDF above the Lossless level, and Unlock PDF — which need a server to do the job properly; those files are processed and discarded straight away, and are never stored or shared.",
  },
  {
    id: "faq-7",
    question: "Can I use these tools on mobile?",
    answer: "Yes. The entire platform is built responsive-first, meaning every tool, layout, and control works on smartphones, tablets, laptops, and wide desktop screens.",
  },
  {
    id: "faq-8",
    question: "How often are new tools added?",
    answer: "We add tools regularly and prioritise the ones people ask for. If there is something you need that is not here yet, send us a request through the contact page — requests genuinely shape what gets built next.",
  },
];
